"""add game Elo ratings

Revision ID: 7094f0900820
Revises: 7be746c6b4fd
Create Date: 2026-09-17 01:22:38.880459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7094f0900820'
down_revision: Union[str, Sequence[str], None] = '7be746c6b4fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('white_elo', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('black_elo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'black_elo')
    op.drop_column('games', 'white_elo')
    # ### end Alembic commands ###
